# This workflow will build a Swift project using Xcode 16.4

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Set up Xcode version 16.4
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    - name: Build
      run: swift build -v
